### ISSUE TITLE
Cache Access Denied

### ISSUE THREAD

**Issue by thebobthebob** [gajus/puppeteer-proxy#13]
`    await page.setRequestInterception(true);

    page.on('request', async (request) => {
      await proxyRequest({
        page,
        proxyUrl: 'https://power-fr.tlsext.com:10799',
        request,
      });
    });`

When I open the page,it shows below wrong message:
Cach Access Denied
The following error was encountered while trying to retrieve the URL: https://google.com/*
Cache Access Denied.
Sorry, you are not currently allowed to request https://google.com/* from this cache until you have authenticated yourself.
Please contact the cache administrator if you have difficulties authenticating yourself.

[Problem Screenshot](https://i.imgur.com/bUNeNYr.png)

How do I solve this problem?

Thank you.

**Comment by gajus** [comment]
This is an issue with the proxy, not with `puppeteer-proxy` itself.
