### ISSUE TITLE
Allow to specifiy proxy URL for HTTP and HTTPS

### ISSUE THREAD

**Issue by Kikobeats** [gajus/puppeteer-proxy#18]
Hello,

Some proxy providers have a different port for HTTP and HTTPS connections

https://github.com/gajus/puppeteer-proxy/blob/f73ecf0eaaef9f18bcd5768739c683a202146e31/src/routines/proxyRequest.js#L123

what if the library exposes a way to provide both things?

Something like that:

```js
agent = {
  http: new HttpProxyAgent(proxyUrl.http || proxyUrl),
  https: new HttpsProxyAgent(proxyUrl.https || proxyUrl)
};
```

**Comment by gajus** [comment]
Of course. Seems like a valid addition.
