### ISSUE TITLE
puppeteer Firefox use page.setRequestInterception throw Fetch.enable RemoteAgentError

### ISSUE THREAD

**Issue by minhuang0** [gajus/puppeteer-proxy#20]
hello,  puppeteer-proxy can support firefox? I didn't find it in the document

this [issues](https://github.com/puppeteer/puppeteer/issues/6359) and [stackoverflow question](https://stackoverflow.com/questions/62065774/setrequestinterception-support-for-firefox-in-puppeteer) is same with me , fireFox not support Fetch.enable

**Comment by gajus** [comment]
This is a Puppeteer issue, not something that can be fixed at this package-level.
