### ISSUE TITLE
Doesn't support HTTPS

### ISSUE THREAD

**Issue by Bouzazi** [gajus/puppeteer-proxy#6]
Works fine with HTTP
Redirecting HTTPS to HTTP
Am i missing something?

**Comment by gajus** [comment]
It certainly works as I am using it for https sites.

You will need to provide more context.

**Comment by Bouzazi** [comment]
Thanks for the quick reply
I'm using the same GET example provided in README with an http proxy bought from proxiware on an HTTPS website, on https://www.howsmyssl.com/ to be exact.
It redirects me to HTTP and tells me that I'm not using a secure connection.

```
import puppeteer from 'puppeteer';
import {
  proxyRequest,
} from 'puppeteer-proxy';

(async () => {
  const browser = await puppeteer.launch({headless: false});
  const page = await browser.newPage();

  await page.setRequestInterception(true);

  page.on('request', async (request) => {
    await proxyRequest({
      page,
      proxyUrl: 'http://us.proxiware.com:3000',
      request,
    });
  });

  await page.goto('https://www.howsmyssl.com/');
})();
```

and I should mention that I'm running it with [esm](https://www.npmjs.com/package/esm) on node

**Comment by gajus** [comment]
Make sure you have `NODE_TLS_REJECT_UNAUTHORIZED=0`.

**Comment by Bouzazi** [comment]
Same result with a warning

> (node:6172) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.

**Comment by gajus** [comment]
¯\\_(ツ)_/¯ 

If you can replicate the issue consistently, then fixing it and writing a test case for it should be easy.

**Comment by Bouzazi** [comment]
I don't know where to start, I'm facing the same issue with this module too [puppeteer-page-proxy ](https://github.com/Cuadrix/puppeteer-page-proxy)
I'm sure it has nothing to do with the proxy itself because It works fine with HTTPS when I use the usual browser implementation.
 
```
const browser = await puppeteer.launch({headless: false, args: ['--proxy-server=http://us.proxiware.com:3021']});
```
and what makes me more indignant is [this](https://i.imgur.com/oOUTC30.png).
Certificate is valid and trusted, all the resources are too. but, It's still showing that my connection is not secure.
