### ISSUE TITLE
Support for socks5 proxy with authentication

### ISSUE THREAD

**Issue by Nik-Novak** [gajus/puppeteer-proxy#7]
I tried to connect to a socks5 proxy with the following proxyUrl property: `socks5://username:password@192.168.1.121:1080`

But it failed with `(node:9488) UnhandledPromiseRejectionWarning: TimeoutError: Navigation timeout of 30000 ms exceeded`

Note this proxy works perfectly as a socks5 proxy in other libraries.

I think if you could add support for authentication and socks5 a lot more people might use this tool

**Comment by gajus** [comment]
Contributions are welcome. It is not a feature I will implement.

**Comment by ordimans** [comment]
It added ?
I have no success to use socks5 proxy with authentification.

**Comment by ordimans** [comment]
It should be working :

```
 if (proxyRequestConfiguration.agent) {
    agent = proxyRequestConfiguration.agent;
  } else if (proxyUrl && request.url().toLowerCase().startsWith('https://')) {
    agent = new HttpsProxyAgent(proxyUrl);
  } else if (proxyUrl) {
    agent = new HttpProxyAgent(proxyUrl);
  }
```

and normally, https-proxy-agent work with this format :
`
var proxy = new HttpsProxyAgent('https://username:password@your-proxy.com');`

see here
https://github.com/TooTallNate/node-https-proxy-agent/issues/12

**Comment by grandzeboma** [comment]
@ordimans maybe it works with https://github.com/Cuadrix/puppeteer-page-proxy ??
I also need authentication

**Comment by ordimans** [comment]
WONDERFUL.
You are a god.
I am looking for since 24h a solution... Didn't find it...
Damn google...
Don't know how did you find it ??


but i tested, and it worked directly, with my socks5 and auth !!!

**Comment by gajus** [comment]
Simply pass [socks-proxy-agent](https://www.npmjs.com/package/socks-proxy-agent) instance to `agent`, e.g.

```js
import puppeteer from 'puppeteer';
import {
  proxyRequest,
} from 'puppeteer-proxy';
import {
  SocksProxyAgent,
} from 'socks-proxy-agent';

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  const agent = {
    http: new SocksProxyAgent('socks5://'),
    https: new SocksProxyAgent('socks5://'),
  };

  await page.setRequestInterception(true);

  page.on('request', async (request) => {
    await proxyRequest({
      agent,
      page,
      proxyUrl: 'http://127.0.0.1:3000',
      request,
    });
  });

  await page.goto('http://gajus.com');
})();

```

Refer to https://github.com/sindresorhus/got#agent

**Comment by dannyokec** [comment]
Please this code doesn't show where to append authentication to the sock5 proxy (username and password), it doesn't show where to input the address, I tried setting the address at the http and https socks 5 url link but none seemed to work

**Comment by sunnyd24** [comment]
Using with authentication details doesn't seem to work with other projects such as FlareSolverr.

See my issue report [on FlareSolverr Github](https://github.com/FlareSolverr/FlareSolverr/issues/387#issue-1221114952)  which points to Puppeteer Proxy limitation that causes this issue.

Any ideas and suggest reopening issue?
