### ISSUE TITLE
Support node 10

### ISSUE THREAD

**Issue by atlanteh** [gajus/puppeteer-proxy#8]
Why does this module specifies engine>10?
Is there a specific issue preventing it from running on NodeJS 10?

**Comment by gajus** [comment]
Just upgrade your Node.js if you are having problems.

**Comment by atlanteh** [comment]
I can't upgrade, but I don't see any problems with engine=10.19.0 so I'm not sure why you require that your module is installed only on engine>=12. 
The only issue I have is that now instead of `yarn add puppeteer-proxy` I need to run `yarn add puppeteer-proxy --ignore-engines`
I think it's safe to change to engine>=10
